#!/bin/bash

_base_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source "$_base_dir/vendor/github.com/reconquest/import.bash/import.bash"

import "github.com/reconquest/blank.bash"

blank:request:new "request" "$@"
